# -*- coding: utf-8 -*-

# This file is part of thumbor-wand-engine
# https://github.com/scorphus/thumbor-wand-engine

# Licensed under the MIT license:
# http://www.opensource.org/licenses/mit-license
# Copyright (c) 2020-2021, Pablo S. Blum de Aguiar <scorphus@gmail.com>

name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-tag:
          - 36
          - 37
          - 38
          - 39
    container: thumbororg/thumbor-test:${{ matrix.image-tag }}
    steps:
      - name: Install missing APT dependencies
        run: apt update && apt install -y curl git libmagickwand-dev
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.1.1
      - name: Setup
        if: matrix.test-kind != 'LINT_TEST'
        run: make setup-ci
      - name: Run unit tests
        run: make unit
      - name: Run acceptance tests
        run: make acceptance
      - name: Run integration tests
        run: make integration
      - name: Run linters
        run: make lint
      - name: Send coverage stats to Codecov
        if: matrix.image-tag == '39'
        run: bash -c "bash <(curl -s https://codecov.io/bash)"
